version: "3.7"
services:

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    depends_on:
        -  app
    ports:
        - "80:80"
    volumes:
        -  ./app/conf.d:/etc/nginx/conf.d

  app:
    image: app
    depends_on:
      - db
    build:
        context: .
        dockerfile: Dockerfile
    deploy:
       mode: replicated
       replicas: 2

  db:
    container_name: "postgres_db"
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: admin
      POSTGRES_DB: db

    ports:
      - "5432:5432"
