version: "3.7"
services:

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    depends_on:
        -  app
        -  app2
    ports:
        - "80:80"
    volumes:
        -  ./app/conf.d:/etc/nginx/conf.d

  app:
    container_name: "app"
    image: app
    build:
        context: .
        dockerfile: Dockerfile

  app2:
    container_name: "app2"
    image: app
    build:
        context: .
        dockerfile: Dockerfile
