name: Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: |
              poetry config virtualenvs.in-project true
              poetry install --no-root

      - name: Install pytest
        run:  poetry add pytest

      - name: Test with pytest
        run: pytest test_read_users.py --doctest-modules --junitxml=junit/test-results.xml
