name: Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install starlette
          pip install httpx
      - name: Test with pytest
        run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml